### ISSUE TITLE
Compatible with Warden/Devise?

### ISSUE THREAD

**Issue by JanStevens** [antulik/pagelet_rails#3]
Hello,

Testing this gem out for a small project, I always have a current logged in user that I want to show pagelets for. When trying to render a page with a pagelet I receive the following error

```
Devise::MissingWarden - Devise could not find the `Warden::Proxy` instance on your request environment.
Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you.:
  devise (4.2.0) lib/devise/controllers/helpers.rb:141:in `warden'
  devise (4.2.0) lib/devise/controllers/helpers.rb:116:in `authenticate_user!'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
  actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  pagelet_rails (0.1.5) lib/pagelet_rails/concerns/response_wrapper.rb:5:in `process_action'
  actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
  actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
  pagelet_rails (0.1.5) app/helpers/pagelets_helper.rb:95:in `pagelet'
```

**Comment by antulik** [comment]
@JanStevens should be fixed in 0.1.6. If you'll have any issues please let me.
