### ISSUE TITLE
Rendering error - Key must be 32 bytes

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#6]
Error on `<%= pagelet :pagelets_notification_bar %>`
> key must be 32 bytes

Controllers
```
class PageletController < ApplicationController
  include PageletRails::Concerns::Controller
end
```

```
class NotificationBar::NotificationBarController < ::PageletController
  pagelet_resource only: [:show]
  def show; end
end
```

show.erb
```
<a href="#" class="button -link">
  <span class="text-center notification-circle">1</span> Notifications
</a>
```

view
```
<ul class="layout horizontal center">
    <li><%= pagelet :pagelets_notification_bar %></li>
</ul>
```

app.js
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require turboboost/turboboost
//= require pagelet_rails

//= require_tree ./libs
//= require_tree ./modules
//= require_tree ./initializers
```

stack
```
ArgumentError - key must be 32 bytes:
  activesupport (5.0.2) lib/active_support/message_encryptor.rb:79:in `_encrypt'
  activesupport (5.0.2) lib/active_support/message_encryptor.rb:60:in `encrypt_and_sign'
  pagelet_rails (0.1.6) lib/pagelet_rails/encryptor.rb:32:in `encode'
  pagelet_rails (0.1.6) lib/pagelet_rails/encryptor.rb:8:in `encode'
  pagelet_rails (0.1.6) lib/pagelet_rails/concerns/controller.rb:60:in `pagelet_encoded_original_options'
  actionpack (5.0.2) lib/abstract_controller/helpers.rb:68:in `pagelet_encoded_original_options'
  pagelet_rails (0.1.6) app/helpers/pagelets_helper.rb:13:in `html_container_attributes'
  pagelet_rails (0.1.6) app/views/layouts/pagelet_rails/container.erb:5:in `___sers_kristiangerardsson__rbenv_versions_______lib_ruby_gems_______gems_pagelet_rails_______app_views_layouts_pagelet_rails_container_erb__3240616986021089150_70136524555280'
  actionview (5.0.2) lib/action_view/template.rb:159:in `block in render'
````

rails 5.0.2

Something I'm doing, or bug? :)

**Comment by antulik** [comment]
What's the output of `Rails.application.secrets[:secret_key_base]` ?

and do you have something like that in `config/secrets.yml`?
```yaml
development:
  secret_key_base: xxxx
```

**Comment by Frexuz** [comment]
```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 760ba71239f03cacbe143047259304b6825288c1ea36a2f6e9d438664822425c72d8742276536cbe3cb7ac0603f0f7d42e69d62abba3452452d5fa78cadaa71a
  signature_cipher_key: a5da3b4a7f9a1a8284289de4da02ded80ce38c2ad17fdb688602a9621e88d7f4

test:
  secret_key_base: adc804aaa601b4bbc4e7d2b0be8fe44441969107ab3b44f9956eb266cacb8898450366941c1a6ec9876b0ea96b7b46e11a8d3a30b2d366f7298a7572c4de04d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

**Comment by antulik** [comment]
Turns out it's an external issue. Please see https://github.com/rails/rails/issues/25185

**Comment by Frexuz** [comment]
Thanks!
